<a href="https://colab.research.google.com/github/aaryagore/ML_basics/blob/main/pandas-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [7]:
ipl_df = pd.read_csv('Players.csv')

In [17]:
ipl_df.head()

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [18]:
ipl_df.shape

(566, 5)

In [20]:
ipl_df.head()

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [22]:
ipl_df.tail()

      Player_Name        DOB Batting_Hand           Bowling_Skill   Country
561   Younis Khan 1977-11-29   Right_Hand        Right-arm medium  Pakistan
562     YS Chahal 1990-07-23   Right_Hand         Legbreak googly     India
563  Yuvraj Singh 1981-12-12    Left_Hand  Slow left-arm orthodox     India
564   YV Takawale 1984-11-05   Right_Hand                     NaN     India
565        Z Khan 1978-10-07   Right_Hand    Left-arm fast-medium     India

In [24]:
ipl_df.info() # gives info of indices, not null count, dtype, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player_Name    566 non-null    object
 1   DOB            471 non-null    datetime64[ns]
 2   Batting_Hand   563 non-null    object
 3   Bowling_Skill  502 non-null    object
 4   Country        471 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 22.2+ KB

In [25]:
ipl_df.columns

Index(['Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill', 'Country'], dtype='object')

In [26]:
ipl_df.isnull()

     Player_Name    DOB  Batting_Hand  Bowling_Skill  Country
0          False  False         False          False    False
1          False  False         False          False    False
2          False  False         False          False    False
3          False   True         False          False     True
4          False   True         False          False     True
..           ...    ...           ...            ...      ...
561        False  False         False          False    False
562        False  False         False          False    False
563        False  False         False          False    False
564        False  False         False           True    False
565        False  False         False          False    False

[566 rows x 5 columns]

In [27]:
ipl_df.isnull().sum()

Player_Name       0
DOB              95
Batting_Hand      3
Bowling_Skill    64
Country          95
dtype: int64

In [29]:
ipl_df.describe() # gives count(not- null values), mean, min,max etc

                                 DOB
count                            471
mean   1984-11-15 10:48:09.171974528
min              1969-06-30 00:00:00
25%              1981-05-21 00:00:00
50%              1985-01-25 00:00:00
75%              1989-02-14 12:00:00
max              1998-07-18 00:00:00

In [30]:
ipl_df.count()

Player_Name      566
DOB              471
Batting_Hand     563
Bowling_Skill    502
Country          471
dtype: int64

In [33]:
ipl_df.mean(numeric_only = True)

Series([], dtype: float64)

In [34]:
ipl_df.std(numeric_only = True)

Series([], dtype: float64)

In [35]:
ipl_df.describe()

                                 DOB
count                            471
mean   1984-11-15 10:48:09.171974528
min              1969-06-30 00:00:00
25%              1981-05-21 00:00:00
50%              1985-01-25 00:00:00
75%              1989-02-14 12:00:00
max              1998-07-18 00:00:00

In [36]:
ipl_df.min(numeric_only = True)

Series([], dtype: float64)

In [38]:
ipl_df.max(numeric_only= True)

Series([], dtype: float64)

In [39]:
ipl_df.sample(5) #gives random 5 values

    Player_Name        DOB Batting_Hand           Bowling_Skill    Country
304   MJ Clarke 1981-04-02   Right_Hand  Slow left-arm orthodox  Australia
548    W Jaffer 1978-02-16   Right_Hand      Right-arm offbreak      India
78    BA Stokes        NaT    Left_Hand   Right-arm fast-medium        NaN
510    T Curran        NaT   Right_hand   Right-arm fast-medium        NaN
40   AG Murtaza 1990-01-01    Left_Hand  Slow left-arm orthodox      India

In [40]:
ipl_df.iloc[0] #gives info of 0th index place

Player_Name           A Ashish Reddy
DOB              1991-02-24 00:00:00
Batting_Hand              Right_Hand
Bowling_Skill       Right-arm medium
Country                        India
Name: 0, dtype: object

In [41]:
ipl_df.iloc[0:5]

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [42]:
ipl_df.columns

Index(['Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill', 'Country'], dtype='object')

In [54]:
ipl_df[['Player_Name','Country']] if 'Player_Name' in ipl_df.columns  else ipl_df.iloc[:,0:2]

        Player_Name   Country
0    A Ashish Reddy     India
1        A Chandila     India
2          A Chopra     India
3       A Choudhary       NaN
4       A Dananjaya       NaN
..              ...       ...
561     Younis Khan  Pakistan
562       YS Chahal     India
563    Yuvraj Singh     India
564     YV Takawale     India
565          Z Khan     India

[566 rows x 2 columns]

In [55]:
ipl_df[ipl_df['runs'] > 500] if 'runs' in ipl_df.columns else ipl_df.head()

      Player_Name        DOB Batting_Hand         Bowling_Skill Country
0  A Ashish Reddy 1991-02-24   Right_Hand      Right-arm medium   India
1      A Chandila 1983-12-05   Right_Hand    Right-arm offbreak   India
2        A Chopra 1977-09-19   Right_Hand    Right-arm offbreak   India
3     A Choudhary        NaT   Right_hand  Left-arm fast-medium     NaN
4     A Dananjaya        NaT   Right_Hand    Right-arm offbreak     NaN

In [10]:
ipl_df.sort_values('Player_Name', ascending=False).head() if 'Player_Name' in ipl_df.columns else ipl_df.head()

       Player_Name        DOB Batting_Hand           Bowling_Skill   Country
565         Z Khan   7-Oct-78   Right_Hand    Left-arm fast-medium     India
563   Yuvraj Singh  12-Dec-81    Left_Hand  Slow left-arm orthodox     India
561    Younis Khan  29-Nov-77   Right_Hand        Right-arm medium  Pakistan
559  Yashpal Singh  27-Nov-81   Right_Hand        Right-arm medium     India
564    YV Takawale   5-Nov-84   Right_Hand                     NaN     India

In [11]:
ipl_df.iloc[:,0].nunique() # finds unique values in column

566

In [12]:
ipl_df.duplicated().sum() #checks duplicate records

np.int64(0)

In [13]:
if{'runs','matches'}.issubset(ipl_df.columns):
  ipl_df['Runs_Per_Match'] = ipl_df['runs'] / ipl_df['matches'] # creating a new feature

In [15]:
ipl_df[['DOB','Player_Name']].head()

         DOB     Player_Name
0  24-Feb-91  A Ashish Reddy
1   5-Dec-83      A Chandila
2  19-Sep-77        A Chopra
3        NaN     A Choudhary
4        NaN     A Dananjaya

In [17]:
if 'Player_Name' not in ipl_df.columns and 'DOB' in ipl_df.columns:
  ipl_df['Player_Type'] = np.where(ipl_df['wickets'] > 50, 'Bowler', 'Batter')
ipl_df['Player_Type'].value_counts() if 'Player_Type' in ipl_df.columns else 'Column unavailable'  # counts category occurences

'Column unavailable'

In [ ]:
ipl_df.groupby()